# Numpy arrays and basics 


import numpy as np

In [26]:
import numpy as np

### 1)numpy array

In [27]:
arr_1d= np.array([1,2,3,4,5])
print(f'1d array ={arr_1d}')

arr_2d= np.array([[1,2,3,],[3,4,5]])
print(f'2d array is {arr_2d}')


1d array =[1 2 3 4 5]
2d array is [[1 2 3]
 [3 4 5]]


## list vs numpy array

In [28]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)




Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


### time module is used to calculate the time

In [29]:

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.1130216121673584

 Numpy operation time:  0.025313138961791992


### creating array from scratch 

* to create an array with only zeros 

In [30]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


* to create the array with only ones 

In [31]:
ones = np.ones((2, 3))
print("one array: \n", ones)

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


* to create an array with any constant 

In [32]:
full = np.full((2, 2), 7)
print("full array: \n", full)


full array: 
 [[7 7]
 [7 7]]


* to generate any random value 
* we use different random methods like randint and rand etc

In [33]:
random = np.random.random((2, 3))
print("random array: \n", random)

random array: 
 [[0.12800115 0.38115606 0.61584614]
 [0.6148174  0.7345215  0.90593414]]


### How to make an array filled with any value
 * numpy have a method named full

In [34]:
np.full(shape = (3,5), fill_value = 'cat')
# array([['cat', 'cat', 'cat', 'cat', 'cat'],
#        ['cat', 'cat', 'cat', 'cat', 'cat'],
#        ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

* to get the elements from a 2-d array 

1) to get first row as a 1-d array

In [35]:
bar = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
])


print(bar)
# [[ 5 10 15 20]
#  [25 30 35 40]
#  [45 50 55 60]]

print(bar[0])
# [ 5 10 15 20]

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[ 5 10 15 20]


2) to get the first row as a 2-d array  

In [36]:
print(bar)

print(bar[0, None])
# [[ 5 10 15 20]]

# Alternate method


print(bar)

print(bar[:1])
# [[ 5 10 15 20]]

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[ 5 10 15 20]]
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[ 5 10 15 20]]


### Arange in array 

* it works like the range in th for loop similarly it takes the (start,stop,step) values and the stop value is non inclusive that means it will not be included 

In [37]:
sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

sequnce array: 
 [ 0  2  4  6  8 10]


## Vector, Matrix & Tensor 

1) vector ( basically an 1-d array)

In [38]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

Vector:  [1 2 3]


2) matrix ( it is in the form of mxn where m is th number of rows and n is the number of columns )

In [39]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

Matrix:  [[1 2 3]
 [4 5 6]]


3) Tensor ( it is nothing but just an complex matrix with the entries of the matrix also become the matrix )

In [40]:
tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties 

1) to tell the shap of an array 

In [41]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)

Shape  (2, 3)


2) to tell the dimension of any matrix

In [42]:
print("Dimension ", arr.ndim)

Dimension  2


3) to tell the size of any array

In [43]:
print("Size ", arr.size)

Size  6


4) to tell the data type of any array 

In [44]:
print("DType ", arr.dtype)

DType  int64


5) to calculate the length 

In [45]:
print(len(arr))

2


You might be surprised to see arr_2d has length 2, not 10. That's because arr_2d can be interpreted as an array that contains 2 arrays inside it. If you want to get the total number of nested elements in the array, you can use the array size attribute.

## some key points to note 

In [46]:
# arr2=np.array([
#     [1, 2, 3, 4],
#     [5, 6]
# ])
# array([list([1, 2, 3, 4]), list([5, 6])], dtype=object)

If you try to make an array from jagged lists like this, numpy doesn't error but it creates an array of objects. This means the array is essentially a Python list and lacks the performance benefits of using an array.
also this will throw an error like it contains some inhomogenous type of elements it contains 2 rows and some inhomogenous data

## Array Reshaping 

In [47]:
arr = np.arange(12)
print("Original array ", arr) # this will generate an array from 0 to 11 

reshaped = arr.reshape((3, 4)) # this will reshape the array 
print("\n Reshaped array ", reshaped)

# note:- the array can only be reshaped according to the numbr of elements it have as mxn array can be converted only by the array having m*n elements 
# example a array having 12 elements can only generate an array with the dimension of 3x4 or 4x3 or 6x2 or 2x6 or 1x12 or 12x1 

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)
# this basically converts the array into 1-d array that means flattening the array 

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)


#[[1,2,3,4,5,6]] this is treated like a 1x6 matrix in python
# and [1,2,3,4,5,6] this is an 1-d array  

# Transpose
transpose = reshaped.T # it does the transpose of the reshaped matrix 
print("\n Transposed array ", transpose) # transpos of a matrix is nothing but making a mxn matrix into nxm 

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##  flatten() always returns a copy of the original array, whereas ravel() returns a view of the original array whenever possible.

# NumPy: `flatten()` vs `ravel()`

The primary difference between `flatten()` and `ravel()` is memory allocation:
* **`flatten()`** always returns a **copy** of the original array.
* **`ravel()`** returns a **view** (reference) of the original array whenever possible.

---

## 📊 Quick Comparison

| Feature | `array.flatten()` | `array.ravel()` / `np.ravel(array)` |
| :--- | :--- | :--- |
| **Memory** | Always allocates new memory (**Copy**) | Shares memory with the original array (**View**) |
| **Data Mutation** | Modifying the output **does not** affect the original | Modifying the output **will change** the original |
| **Performance** | Slower (requires copying data blocks) | Faster (avoids data duplication) |
| **Syntax Type** | Only available as an `ndarray` method | Available as a function and an `ndarray` method |
| **Input Flexibility**| Requires a strict NumPy array | Accepts non-array structures (e.g., standard lists) |


## 💻 Code Examples

### 1. Modifying a `flatten()` Array (Safe & Isolated)
Because `flatten()` generates a distinct deep copy, changing its elements leaves the parent matrix completely untouched.
```python
import numpy as np

original = np.array([[1, 2], [3, 4]])
flat_arr = original.flatten()

# Modify the 1D array
flat_arr[0] = 99

print("Flattened:", flat_arr)
print("Original:\n", original)  # Unchanged
```

### 2. Modifying a `ravel()` Array (Shared Memory)
Because `ravel()` defaults to a view, mutating the 1D output directly updates the source matrix.

```python
import numpy as np

original = np.array([[1, 2], [3, 4]])
ravel_arr = original.ravel()

# Modify the 1D array
ravel_arr[0] = 99

print("Raveled:", ravel_arr)
print("Original:\n", original)  # Original changes!
```
*> **Note:** If the original array consists of non-contiguous memory slices, `ravel()` will automatically fallback to creating a copy instead of a view.*

---

## 💡 Summary Rule of Thumb
* Use **`ravel()`** for read-only loops, math metrics, or when you explicitly want changes to sync back to the main matrix. It optimizes speed and memory.
* Use **`flatten()`** when you plan to manipulate the 1D array separately and must guarantee that your original multi-dimensional dataset remains protected.


In [48]:

#in detail ravel 


# Create a 2D array (2 rows, 3 columns)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# Flatten the array
flat_view = np.ravel(matrix)
print(flat_view)  
# Output: [1 2 3 4 5 6]

# Modifying the view changes the original matrix!
flat_view[0] = 99
print(matrix)
# Output: 
# [[99  2  3]
#  [ 4  5  6]]

[1 2 3 4 5 6]
[[99  2  3]
 [ 4  5  6]]
