# NUMPY ARRAY OPERATIONS

In [2]:
import numpy as np 

## SLICING in Array

* slicing in 1d array

In [3]:
arr= np.array([1,2,3,4,5,6,7,8,9,10]) 
print('basic slicing',arr[2:7])
print('step slicing',arr[2:9:2])
print('negative indexing',arr[-3])


basic slicing [3 4 5 6 7]
step slicing [3 5 7 9]
negative indexing 8


* slicing in 2d array 

In [4]:
arr_2d= np.array([[1,2,3], # 0th row is this 
                  [4,5,6], # 1st row is this
                  [7,8,9]]) # 2nd row is this 
# just like the row the indexing of columns also starts with 0
print('specific element',arr_2d[1,2]) # this means the element at 1st row and 2nd column
print('entire row: ',arr_2d[1]) # to print one complete row
print('specific column: ',arr_2d[:,1])

specific element 6
entire row:  [4 5 6]
specific column:  [2 5 8]


## Sorting

In [5]:
unsorted=np.array([3,1,4,1,5,9,2,6])


* sort method is used for sorting any array in numpy

In [6]:
print('sorted array: \n',np.sort(unsorted)) # sorting in 1d array

sorted array: 
 [1 1 2 3 4 5 6 9]


* for 2d array

In [7]:
unsorted_2d=np.array([[1,2],[2,3],[3,1]])
print('sorted array column wise:\n',np.sort(unsorted_2d,axis=0)) # sorting from top to bottom
print('sorted array with rows:\n',np.sort(unsorted_2d,axis=1)) # sorting from left to right

sorted array column wise:
 [[1 1]
 [2 2]
 [3 3]]
sorted array with rows:
 [[1 2]
 [2 3]
 [1 3]]


## Filtering the array

In [8]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print('even numbers:',even_number)

even numbers: [ 2  4  6  8 10]


## Filter with mask

In [9]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])
# mask basically act as an container which stores the condition 

Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indxing vs np.where()

In [ ]:
indices = [0, 2, 4] # this indicates the 0th 2nd and the 4th value according to indexing 
print(numbers[indices])


[1 3 5]


### where ( it basically acts as sql where clause)

In [12]:
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


### where have three things 
where ( condition, x, y)

In [14]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array) 
# it basically wors as if-else 
# if condition ==true
# do x ( the condition/ task given at the position of x )
# else 
# do y ( the statement written at the position of y)

# this example basically does that where the condition becomes true write true and where the conditon is not true write fale 

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [15]:
condition_array = np.where(numbers > 5, "true",  numbers)
print(condition_array) 

['1' '2' '3' '4' '5' 'true' 'true' 'true' 'true' 'true']


### Adding & Removing data

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatability 

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vstack also known as verticle stack used to add new row 
print(original) 
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) #hstack also known as horizontal stack used to add new column 
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


* for deleting from array 

In [19]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]


it doesnot give the deleted value instead it gives the whole array after deletion 