In [3]:
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.random.rand(3,3)
array3=np.zeros((4,4))

In [5]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [6]:
loaded_array=np.load('array2.npy')
print(loaded_array)

[[0.57213283 0.99918104 0.27401066]
 [0.34111269 0.87295763 0.05663342]
 [0.95168277 0.13516358 0.73390931]]


## 3-D Array 


In [7]:
zoo = np.array([
    [
        [10,20],
        [30,40],
        [50,60],
    ],
    [
        [11,12],
        [13,14],
        [15,16],
    ]
])

print(zoo)


# a 3-d array is basically like a tensor

[[[10 20]
  [30 40]
  [50 60]]

 [[11 12]
  [13 14]
  [15 16]]]


* and you make an assignment like zoo[0,:,1] = 5, you can interpret the assignment as  **`set the 1st matrix, every row, 2nd column equal to 5`**

In [8]:
zoo[0,:,1] = 5

print(zoo)
# [[[10  5]
#   [30  5]
#   [50  5]]
#  [[11 12]
#   [13 14]
#   [15 16]]]

[[[10  5]
  [30  5]
  [50  5]]

 [[11 12]
  [13 14]
  [15 16]]]


### some key points to note 

 we use @ operation to do any matrix multiplication between two array 

Broadcasting Arithmetic
If you do foo + 5, numpy adds 5 to each element of foo.

# np.linspace 

linspace
Return evenly spaced numbers over a specified interval.

In [9]:
arr=np.linspace(0,10,3)

In [10]:
print(arr)

[ 0.  5. 10.]


In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### this basically means that from starting with 0 to 10 and here both 0 and 10 are inclusive give me sequence which cintains 50 elements and all are evenly spaced 

# Intermediate Level

* ***` np.new axis `***\
np.newaxis allows us to promote the dimensionality of an array by giving it a new axis.

## Matrix Broadcasting and Difference Matrices

Suppose you have two 1-D arrays, \(A\) and \(B\):

```python
import numpy as np

A = np.array([3, 11, 4, 5])
B = np.array([5, 0, 3])
```

Your goal is to build a difference matrix where each element at position \((i, j)\) gives:
\[C_{i, j} = A_i - B_j\]

In other words, you want to subtract each element of \(B\) from each element of \(A\).

---

### The Challenge with 1-D Arrays

If you try to run `A - B`, NumPy will throw a `ValueError` because the arrays do not have compatible shapes for direct operation:

```text
ValueError: operands could not be broadcast together with shapes (4,) (3,)
```

Even if they were the exact same size, NumPy would only perform simple element-wise subtraction instead of generating a full cross-difference matrix.

---

### The Broadcasting Solution

If \(A\) is transformed into a \(4 x 1\) array and \(B\) is transformed into a \(1 x 3\) array, NumPy broadcasting rules will automatically expand both arrays to produce the desired difference matrix.

#### 1. Reshape Array \(A\)
Convert \(A\) from shape `(4,)` into a `(4, 1)` column vector using `np.newaxis`:

```python
A[:, np.newaxis]
```
**Output:**
```python
array([[ 3],
,
       [ 4],
       [ 5]])
```

#### 2. Reshape Array \(B\)
Convert \(B\) from shape `(3,)` into a `(1, 3)` row vector:

```python
B[np.newaxis, :]
```
**Output:**
```python
array([[5, 0, 3]])
```

#### 3. Calculate the Difference Matrix

```python
A[:, np.newaxis] - B[np.newaxis, :]
```
**Output:**
```python
array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])
```

---

### Shortcuts & Simplifications

#### Vector-to-Array Broadcasting
You can simplify the syntax to `A[:, np.newaxis] - B`. NumPy broadcasting automatically treats the 1-D array \(B\) as a row vector to match the 2-D column vector:

```python
A[:, np.newaxis] - B
```

#### Using `None`
`np.newaxis` is an alias for `None`. You can write the expression even more concisely like this:

```python
A[:, None] - B
```


####

# Boolean Indexing

With boolean indexing, you can subset an array `A` using another array `B` composed of boolean values (`True`/`False`).

---

## Example Walkthrough

### 1. Define the Initial Array
Suppose we have a \(3 \times 3\) array named `foo`:

```python
import numpy as np

foo = np.array([,
 ,
    [3, 3, 1]
])
```

---

### 2. Create a Comparison Mask
We can generate a boolean mask to find everywhere the value equals `3`:

```python
mask = foo == 3
print(mask)
```

**Output:**
```python
[[ True False False]
 [False False  True]
 [ True  True False]]
```

---

### 3. Subset the Array Using the Mask
We can apply this `mask` back to `foo` to isolate and extract only the elements that match our condition:

```python
print(foo[mask])
```

**Output:**
```python
[3 3 3 3]
```

---

### 4. Modify Values In-Place
Furthermore, we can use the exact same `mask` to modify elements conditionally—for example, converting all `3`s in `foo` to `0`s:

```python
foo[mask] = 0
print(foo)
```

**Output:**
```python
[[0 9 7]
 [2 0 0]
 [0 0 1]]
```


In [12]:
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

In [13]:
r13 = np.array([True, False, True])
c23 = np.array([False, True, True])

In [16]:
# to get the columns 
print(foo[:,c23])


# to get the rows 
print(foo[r13])

[[9 7]
 [0 3]
 [3 1]]
[[3 9 7]
 [3 3 1]]
