# Problem Statement 1 

1) With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday. \
Given these daily weights, build an array with your average weight per weekend

In [2]:
import numpy as np 

In [4]:
dailywts = 185 - np.arange(5*7)/5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [5]:
# to build an array with average
print((dailywts[5::7]+dailywts[6::7])/2)


[183.9 182.5 181.1 179.7 178.3]


## Explaination

### Weekend Weight Analysis

We can use slicing to get the weights for every Saturday. Keep in mind that index `0` represents a Monday, so the first Saturday occurs at index `5`.

```python
dailywts[5::7]  
# Output: array([184. , 182.6, 181.2, 179.8, 178.4])
```

Similarly, we can use `dailywts[6::7]` to select the weights for every Sunday.

```python
dailywts[6::7]
# Output: array([183.8, 182.4, 181. , 179.6, 178.2])
```

We can calculate the total weight per weekend by adding these same-sized arrays together.

```python
dailywts[5::7] + dailywts[6::7]  
# Output: array([367.8, 365. , 362.2, 359.4, 356.6])
```

Lastly, we can get the average weight per weekend by dividing the previous array by `2`.

```python
(dailywts[5::7] + dailywts[6::7]) / 2  
# Output: array([183.9, 182.5, 181.1, 179.7, 178.3])
```


# Problem Statement 2

2) Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row\
[[ 1  3  5  7  9 11 13]\
 [17 19 21 23 25 27 29]\
 [33 35 37 39 41 43 45]\
 [49 51 53 55 57 59 61]]

In [6]:
nola=np.arange(start=1,stop=65,step=2)

In [16]:
print(nola)
rehsaped=nola.reshape((4,-1)) # this means the number of row should be 4 and the -1 given at columns means look at th total number of elements in the array and automatically calculate how many columns are needed 
print(rehsaped) # this will reshape the array 


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63]
[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47]
 [49 51 53 55 57 59 61 63]]


In [18]:
# other way to write this is
nola = np.arange(start=1, stop=65, step=2).reshape(4,8)

In [19]:
print(nola)

[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47]
 [49 51 53 55 57 59 61 63]]


In [ ]:
nola=nola[:,:-1]# this means select all the rows and select all the columns from the start but upto the last one 

In [ ]:
print(nola) # the upper part of the code will completely chop off the last column from the code 

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


# Problem Statement 3

3) After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

``` python
import numpy as np

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)
# [[2 3 0 5 2 0 3]
#  [8 8 0 7 1 5 3]
#  [0 1 6 2 1 4 5]
#  [4 0 8 9 9 8 7]
#  [4 2 7 0 7 2 1]
#  [9 8 9 2 5 0 8]
#  [1 9 8 2 6 4 3]]

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
```

Notes
* gold states how much gold is under each location in the 7x7 grid of land
* locs states the coordinates of the five locations where you dig

In [24]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)
# [[2 3 0 5 2 0 3]
#  [8 8 0 7 1 5 3]
#  [0 1 6 2 1 4 5]
#  [4 0 8 9 9 8 7]
#  [4 2 7 0 7 2 1]
#  [9 8 9 2 5 0 8]
#  [1 9 8 2 6 4 3]]

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


## Numpy Seed 
It tells NumPy: **`Start your random number formula from position 5555.`**"
Think of it like a recipe book with thousands of pages, where each page has a different sequence of "random" numbers already written down. Calling np.random.seed(5555) is like saying "open the book to page 5555 and start reading numbers from there."
Why does this matter?

* If you don't set a seed, NumPy picks a different starting point every time (often based on the current time), so your "random" numbers change every time you run the code.
* If you do set a seed (like 5555), NumPy always starts from that same page. So every single time you run the code — today, tomorrow, on a different computer — you get the exact same sequence of "random" numbers.

## Solution 

the array gold is a 7x7 matrix with rows 0 to 6 and columns 0 to 6\
locs give fiv coordinate pairs [rows,columns]- these are the spots you dig\
at[0,4] in gold we have 2 at [2,2] in gold we have 6

In [25]:
results=gold[locs[:,0],locs[:,1]]
print(results)

[2 6 2 8 2]


## Explaination

* locs[:, 0] grabs the first column of locs → all the row numbers: [0, 2, 2, 5, 6]
* locs[:, 1] grabs the second column of locs → all the column numbers: [4, 2, 3, 1, 3]
* gold[rows, cols] then pulls out gold[0,4], gold[2,2], gold[2,3], gold[5,1], gold[6,3] — one matched pair at a time, in order.

2) second method to solve 

* using the loop 

In [26]:
np.random.seed(5555)
gold=np.random.randint(low=0,high=10,size=(7,7))
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [27]:
locs= np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [34]:
results=[]
for loc in locs:
    row=loc[0]
    col=loc[1]
    value=gold[row,col]
    results.append(value)
print('all results',results)
print('total sum is',sum(results))

all results [np.int32(2), np.int32(6), np.int32(2), np.int32(8), np.int32(2)]
total sum is 20


# Why This Happens

When you do `value = gold[row, col]`, you're not getting back a plain Python integer. You're getting back a NumPy scalar type, specifically `np.int32` (or `np.int64`, depending on your system).

### The Core Reason
`gold` is a NumPy array, and NumPy arrays store all their elements as a single fixed data type (called `dtype`). When you slice or index into a NumPy array, NumPy doesn't convert the result back into a native Python `int`. Instead, it gives you back one of its own internal NumPy types, wrapped to look like a single number.

So `gold[row, col]` isn't a Python `int`. It's an `np.int32` — a NumPy-specific way of representing an integer. It behaves almost identically to a Python `int` (you can add it, print it, and compare it), but it is not the exact same type.

---

### Why does it show up as `np.int32(2)` in your list?

When you `print(results)` and `results` is a plain Python `list` containing NumPy scalar objects, Python's `repr()` for each item shows you exactly what type it is — hence `np.int32(2)` instead of just `2`.

If your `results` had been plain Python integers, it would've printed simply:

```python
[2, 6, 2, 8, 2]
```

But since each `value` came directly from indexing a NumPy array, each one carries along its NumPy type, and the list stores them as-is.

---

### Why didn't this happen with `gold[locs[:,0], locs[:,1]]`?

Good question — it actually **did** happen there too, but it looked different. 

Fancy indexing (`gold[locs[:,0], locs[:,1]]`) returns a NumPy array, not a Python list. NumPy arrays print their contents using `np.array2string`, which suppresses the `np.int32(...)` wrapper and just shows the bare numbers:

```text
[2 6 2 8 2]
```

### Conclusion
The difference you're seeing isn't really about the values being different — it's about how each container (list vs array) chooses to display its contents.


### to resolve this you can do 

```python 
value = int(gold[row, col])
```

# Problem Statement 3

Define a  roux array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.\

Examples

* roux array of length 5\
[9 0 4 0 1]
* roux array of length 8\
[ 0 16  0  9  0  4  0  1]
* roux array of length 12\
[ 0 36  0 25  0 16  0  9  0  4  0  1]\
Note: odd-length arrays begin with a square number while even-length arrays begin with a zero.

Implement a function called make_roux(n) that inputs n, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above.

def make_roux(n):\
    """returns a roux array of length n"""

    # your code here

In [ ]:
def make_roux(n):
    seq=np.zeros(n,dtype=int) #dtype=int makes sure these are integers, not floats (NumPy defaults zeros() to floats otherwise).
    square=1
    for i in range(0,n,2):
        seq[i]=square**2
        square+=1
    print(seq)
    return seq[::-1]

make_roux(6)


[1 0 4 0 9 0]


array([0, 9, 0, 4, 0, 1])

In [43]:
def make_roux2(n):
    seq=np.zeros(n,dtype=int)
    num_square=(n+1)//2
    squares=(np.arange(1,num_square+1))**2
    seq[::2]=squares
    return seq[::-1]
make_roux2(5)

array([9, 0, 4, 0, 1])

## Line-by-Line Code Breakdown

---

### 1. Initialize the Base Array
```python
seq = np.zeros(n, dtype=int)
```
* **Function:** Creates an array of length `n`, filled entirely with zeros.
* **Example (n=8):** `[0 0 0 0 0 0 0 0]`
* **Note:** `dtype=int` ensures these are integers. NumPy defaults `zeros()` to floats otherwise.

---

### 2. Calculate the Number of Required Squares
```python
num_squares = (n + 1) // 2
```
* **Function:** Figures out how many square numbers we will need to place into the array.
* **Logic:** Every other position (the even indices: 0, 2, 4, ...) will hold a square number. For an array of length `n`, the count of even indices is (n + 1) // 2.

**Verification Examples:**

| n | Even Indices | Count | Formula Evaluation |
|---|---|---|---|
| **5** | 0, 2, 4 | 3 | `(5 + 1) // 2` = **3** ✓ |
| **8** | 0, 2, 4, 6 | 4 | `(8 + 1) // 2` = **4** ✓ |
| **12** | 0, 2, 4, 6, 8, 10 | 6 | `(12 + 1) // 2` = **6** ✓ |

---

### 3. Generate the Square Numbers
```python
squares = (np.arange(1, num_squares + 1)) ** 2
```
* **Function:** Builds the actual sequence of square numbers.
* **Step 1:** `np.arange(1, num_squares + 1)` creates a sequence from 1 up to `num_squares`.
* **Step 2:** `** 2` squares every element element-wise without a loop.

**Example (n = 8, `num_squares = 4`):**
* `np.arange(1, 5)` → `[1, 2, 3, 4]`
* `squares` → `[1, 4, 9, 16]`

---

### 4. Insert Squares into Even Indices
```python
seq[0::2] = squares
```
* **Function:** This is the key NumPy trick. 
* **Logic:** `seq[0::2]` uses slice notation meaning *"start at index 0, go to the end, step by 2"* to select all even indices.
* **Execution:** Assigning `squares` to this slice places each number directly into those positions in a single vectorized operation.

**Visual Step (n = 8):**
* **Before:** `[0, 0, 0, 0, 0, 0, 0, 0]` *(Indices: 0, 1, 2, 3, 4, 5, 6, 7)*
* **Operation:** `seq[0::2] = [1, 4, 9, 16]`
* **After:** `[1, 0, 4, 0, 9, 0, 16, 0]`

---

### 5. Reverse and Return the Sequence
```python
return seq[::-1]
```
* **Function:** Reverses the entire array.
* **Logic:** The step of `-1` tells NumPy to read the array backwards.

**Final Transformation:**
`[1, 0, 4, 0, 9, 0, 16, 0]` $\rightarrow$ **Reversed** $\rightarrow$ `[0, 16, 0, 9, 0, 4, 0, 1]`
*(This matches the expected array pattern for $n=8$)*


# Question!

why my code give me the output just after function calling  when i write the return statment in my function i don't have to explicitly store the function return value and then print that

# Answer

* The short answer
You're almost certainly running this in a Jupyter notebook (or an IPython environment, or the Python REPL). These environments have a special behavior:\
They automatically display the value of the last expression in a cell, even without print().\
This is not standard Python behavior — a regular .py script run from the terminal will not do this.\
Why does Jupyter do this?\
Jupyter is built for interactive, exploratory work — you're constantly checking intermediate values without wanting to type print() every single time. So the notebook kernel evaluates each cell and, if the very last line produces a value (and that value isn't None), it shows it as the cell's "Out[]" result.